server:
  port: 9090
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.54:3306/ros?serverTimezone=GMT%2b8
    username: ros
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



mybatis:
  mapper-locations: classpath:mapper/*.xml

weixinconfig:
  weixinappID: wx14a95473b3afe32f
  weixinappSecret: 0e4dcbc736c56929d840cbd25e382ce3

